ktor:
  application:
    modules:
      - ApplicationKt.module
  deployment:
    port: 8080
database:
  connectionUrl: "${DB_URL}:jdbc:postgresql://localhost:5432/postgres"
  user: "${DB_USER}:postgres"
  password: "${DB_PASSWORD}:postgres"