services:
  # PostgreSQL Database
  postgres:
    image: postgres:18.0-alpine
    container_name: money-mgr-db
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d  # Optional: for initialization scripts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-myapp_user}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # Ktor Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: money-mgr-app
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/$DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge